import type { CurriculumLevel, WorldId } from "./types";

/**
 * Catálogo declarativo de los 22 niveles del currículo.
 * Fuente de verdad pedagógica: ../../../docs/CURRICULUM.md §4.
 *
 * "free" sigue el empaquetado comercial de PLAN.md §3: Etapa A completa
 * + una muestra de la Etapa B (N4).
 */
export const CURRICULUM_LEVELS: CurriculumLevel[] = [
  // Etapa A — Descubrimiento (gratis, uso acompañado)
  {
    id: "n1",
    order: 1,
    stage: "A",
    domain: "attention",
    titleKey: "level.n1.title",
    icon: "✨",
    free: true,
    status: "playable",
    area: "descubro",
    world: "estacion",
    ageRange: "0-2",
    skills: ["cause-effect", "attention"],
    difficulty: 1,
    interactionType: "tap",
    learningObjectiveKey: "level.n1.objective",
    category: "jugar",
  },
  {
    id: "n2",
    order: 2,
    stage: "A",
    domain: "attention",
    titleKey: "level.n2.title",
    icon: "🎯",
    free: true,
    status: "playable",
    area: "descubro",
    world: "estacion",
    ageRange: "2-3",
    skills: ["attention", "fine-motor"],
    difficulty: 1,
    interactionType: "tap",
    learningObjectiveKey: "level.n2.objective",
    category: "jugar",
  },
  {
    id: "n3",
    order: 3,
    stage: "A",
    domain: "perception",
    // NO 🧩: ese es el de N6 (Rompecabezas) y ambos viven en El Bosque. El
    // niño no lee los títulos — navega por el ícono, así que dos mosaicos
    // idénticos en el mismo mundo son, para él, el mismo juego dos veces.
    // 👯 = "dos iguales", que es exactamente la mecánica de N3.
    titleKey: "level.n3.title",
    icon: "👯",
    free: true,
    status: "playable",
    area: "descubro",
    world: "bosque",
    ageRange: "2-3",
    skills: ["visual-recognition", "memory"],
    difficulty: 1,
    interactionType: "match",
    learningObjectiveKey: "level.n3.objective",
    category: "jugar",
  },

  // Etapa B — Exploración (muestra gratis: N4; resto de pago)
  {
    id: "n4",
    order: 4,
    stage: "B",
    domain: "categorization",
    titleKey: "level.n4.title",
    icon: "🟥",
    free: true,
    status: "playable",
    area: "pienso",
    world: "estacion",
    ageRange: "2-3",
    skills: ["categorization", "color-recognition", "fine-motor"],
    difficulty: 1,
    interactionType: "drag-and-drop",
    learningObjectiveKey: "level.n4.objective",
    category: "aprender",
  },
  {
    id: "n5",
    order: 5,
    stage: "B",
    domain: "language",
    titleKey: "level.n5.title",
    icon: "🐶",
    free: false,
    status: "playable",
    area: "comunico",
    world: "bosque",
    ageRange: "2-3",
    skills: ["language", "visual-recognition"],
    difficulty: 2,
    interactionType: "listen-and-select",
    learningObjectiveKey: "level.n5.objective",
    category: "aprender",
  },
  {
    id: "n6",
    order: 6,
    stage: "B",
    domain: "spatial",
    titleKey: "level.n6.title",
    icon: "🧩",
    free: false,
    status: "playable",
    area: "pienso",
    world: "bosque",
    ageRange: "3-4",
    skills: ["spatial-reasoning", "fine-motor"],
    difficulty: 2,
    interactionType: "drag-and-drop",
    learningObjectiveKey: "level.n6.objective",
    category: "aprender",
  },
  {
    id: "n7",
    order: 7,
    stage: "B",
    domain: "language",
    axis: "social-emotional",
    titleKey: "level.n7.title",
    icon: "😊",
    free: false,
    status: "playable",
    area: "comprendo",
    world: "bosque",
    ageRange: "3-4",
    skills: ["emotional-recognition", "language"],
    difficulty: 2,
    interactionType: "listen-and-select",
    learningObjectiveKey: "level.n7.objective",
    category: "aprender",
  },
  {
    id: "n8",
    order: 8,
    stage: "B",
    domain: "attention",
    axis: "executive-function",
    titleKey: "level.n8.title",
    icon: "🛑",
    free: false,
    status: "playable",
    area: "resuelvo",
    world: "oceano",
    ageRange: "3-4",
    skills: ["attention", "problem-solving"],
    difficulty: 2,
    interactionType: "tap",
    learningObjectiveKey: "level.n8.objective",
    category: "jugar",
  },

  // Etapa C — Fundamentos (de pago)
  {
    id: "n9",
    order: 9,
    stage: "C",
    domain: "number",
    titleKey: "level.n9.title",
    icon: "🔢",
    free: false,
    status: "playable",
    area: "construyo",
    world: "estacion",
    ageRange: "3-4",
    skills: ["counting", "visual-recognition"],
    difficulty: 2,
    interactionType: "listen-and-select",
    learningObjectiveKey: "level.n9.objective",
    category: "aprender",
  },
  {
    id: "n10",
    order: 10,
    stage: "C",
    domain: "number",
    titleKey: "level.n10.title",
    icon: "🚗",
    free: false,
    status: "playable",
    area: "construyo",
    world: "estacion",
    ageRange: "3-4",
    skills: ["counting", "sequencing"],
    difficulty: 2,
    interactionType: "tap",
    learningObjectiveKey: "level.n10.objective",
    category: "aprender",
  },
  {
    id: "n11",
    order: 11,
    stage: "C",
    domain: "number",
    titleKey: "level.n11.title",
    icon: "🔟",
    free: false,
    status: "playable",
    area: "construyo",
    world: "estacion",
    ageRange: "4-5",
    skills: ["counting", "sequencing"],
    difficulty: 3,
    interactionType: "tap",
    learningObjectiveKey: "level.n11.objective",
    category: "aprender",
  },
  {
    id: "n12",
    order: 12,
    stage: "C",
    domain: "shapes",
    titleKey: "level.n12.title",
    icon: "🔺",
    free: false,
    status: "playable",
    area: "pienso",
    world: "oceano",
    ageRange: "3-4",
    skills: ["shape-recognition", "categorization"],
    difficulty: 2,
    interactionType: "match",
    learningObjectiveKey: "level.n12.objective",
    category: "aprender",
  },
  {
    id: "n13",
    order: 13,
    stage: "C",
    domain: "memory",
    axis: "executive-function",
    titleKey: "level.n13.title",
    icon: "🧠",
    free: false,
    status: "playable",
    area: "resuelvo",
    world: "bosque",
    ageRange: "4-5",
    skills: ["memory", "attention"],
    difficulty: 3,
    interactionType: "match",
    learningObjectiveKey: "level.n13.objective",
    category: "aprender",
  },
  {
    id: "n14",
    order: 14,
    stage: "C",
    domain: "language",
    titleKey: "level.n14.title",
    icon: "🎵",
    free: false,
    status: "coming-soon",
    area: "comunico",
    world: "bosque",
  },
  {
    id: "n15",
    order: 15,
    stage: "C",
    domain: "spatial",
    axis: "social-emotional",
    titleKey: "level.n15.title",
    icon: "📏",
    free: false,
    status: "coming-soon",
    area: "comprendo",
    world: "oceano",
  },
  {
    id: "n16",
    order: 16,
    stage: "C",
    domain: "motor",
    titleKey: "level.n16.title",
    icon: "✏️",
    free: false,
    status: "coming-soon",
    area: "creo",
    world: "bosque",
  },

  // Etapa D — Preescolar (de pago)
  {
    id: "n17",
    order: 17,
    stage: "D",
    domain: "number",
    titleKey: "level.n17.title",
    icon: "2️⃣",
    free: false,
    status: "coming-soon",
    area: "construyo",
    world: "estacion",
  },
  {
    id: "n18",
    order: 18,
    stage: "D",
    domain: "number",
    titleKey: "level.n18.title",
    icon: "➕",
    free: false,
    status: "coming-soon",
    area: "construyo",
    world: "estacion",
  },
  {
    id: "n19",
    order: 19,
    stage: "D",
    domain: "categorization",
    axis: "executive-function",
    titleKey: "level.n19.title",
    icon: "🔄",
    free: false,
    status: "coming-soon",
    area: "resuelvo",
    world: "oceano",
  },
  {
    id: "n20",
    order: 20,
    stage: "D",
    domain: "reading",
    titleKey: "level.n20.title",
    icon: "🔤",
    free: false,
    status: "coming-soon",
    area: "comunico",
    world: "bosque",
  },
  {
    id: "n21",
    order: 21,
    stage: "D",
    domain: "motor",
    titleKey: "level.n21.title",
    icon: "📝",
    free: false,
    status: "coming-soon",
    area: "creo",
    world: "bosque",
  },
  {
    id: "n22",
    order: 22,
    stage: "D",
    domain: "reading",
    titleKey: "level.n22.title",
    icon: "📖",
    free: false,
    status: "coming-soon",
    area: "comunico",
    world: "bosque",
  },
];

export function getLevel(id: string): CurriculumLevel | undefined {
  return CURRICULUM_LEVELS.find((level) => level.id === id);
}

export function getLevelsByStage(stage: CurriculumLevel["stage"]): CurriculumLevel[] {
  return CURRICULUM_LEVELS.filter((level) => level.stage === stage).sort((a, b) => a.order - b.order);
}

export function getLevelsByWorld(world: WorldId): CurriculumLevel[] {
  return CURRICULUM_LEVELS.filter((level) => level.world === world).sort((a, b) => a.order - b.order);
}
